import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { SpaceGrotesk } from "@/lib/fonts";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${SpaceGrotesk.variable} antialiased`}>
        <div id="smooth-wrapper">
          <div id="smooth-content">
            <Header />
            {children}
            <Footer/>
          </div>
        </div>
      </body>
    </html>
  );
}
